"""add_doctor_phone_number

Revision ID: 98965d653844
Revises: b3d4e5f6a7b8
Create Date: 2026-02-09 11:44:52.847201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98965d653844'
down_revision = 'b3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_calendar_sync_next_attempt_at'), 'appointments', ['calendar_sync_next_attempt_at'], unique=False)
    op.drop_constraint('appointments_doctor_email_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_email'], ['email'], ondelete='CASCADE')
    op.drop_constraint('calendar_watches_doctor_email_fkey', 'calendar_watches', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_watches', 'doctors', ['doctor_email'], ['email'], ondelete='CASCADE')
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.drop_constraint('uq_doctor_accounts_doctor_email', 'doctor_accounts', type_='unique')
    op.drop_index('ix_doctor_accounts_doctor_email', table_name='doctor_accounts')
    op.create_index(op.f('ix_doctor_accounts_doctor_email'), 'doctor_accounts', ['doctor_email'], unique=True)
    op.drop_constraint('doctor_leaves_doctor_email_fkey', 'doctor_leaves', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_leaves', 'doctors', ['doctor_email'], ['email'], ondelete='CASCADE')
    op.add_column('doctors', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'phone_number')
    op.drop_constraint(None, 'doctor_leaves', type_='foreignkey')
    op.create_foreign_key('doctor_leaves_doctor_email_fkey', 'doctor_leaves', 'doctors', ['doctor_email'], ['email'])
    op.drop_index(op.f('ix_doctor_accounts_doctor_email'), table_name='doctor_accounts')
    op.create_index('ix_doctor_accounts_doctor_email', 'doctor_accounts', ['doctor_email'], unique=False)
    op.create_unique_constraint('uq_doctor_accounts_doctor_email', 'doctor_accounts', ['doctor_email'])
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_constraint(None, 'calendar_watches', type_='foreignkey')
    op.create_foreign_key('calendar_watches_doctor_email_fkey', 'calendar_watches', 'doctors', ['doctor_email'], ['email'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_doctor_email_fkey', 'appointments', 'doctors', ['doctor_email'], ['email'])
    op.drop_index(op.f('ix_appointments_calendar_sync_next_attempt_at'), table_name='appointments')
    # ### end Alembic commands ###
